# Generated by Django 4.2.2 on 2023-06-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todoitemapi",
            name="user_id",
        ),
        migrations.AddField(
            model_name="todoitemapi",
            name="user_email",
            field=models.EmailField(default="User", max_length=50, unique=True),
        ),
    ]
