# Generated by Django 4.2.2 on 2023-06-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0002_remove_todoitemapi_user_id_todoitemapi_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitemapi",
            name="description",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="todoitemapi",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
