# Generated by Django 4.2.2 on 2023-06-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0003_alter_todoitemapi_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitemapi",
            name="user_email",
            field=models.EmailField(default="User", max_length=50),
        ),
    ]
